version: '3'

services:
    mongo:
        image: mongo
        ports:
        - "27017:27017"
        networks:
            - mongo-compose-network
        container_name: mongo
    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: user
            ME_CONFIG_BASICAUTH_PASSWORD: user
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin
        links:
            - mongo
        networks:
            - mongo-compose-network
        container_name: mongo-express
networks: 
    mongo-compose-network:
        driver: bridge