version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=natours_root_user
      - MONGO_INITDB_ROOT_PASSWORD=natours_root_password
    ports:
      - "27017:27017"
    restart: unless-stopped
  mongo-express:
    image: mongo-express
    container_name: mongoexpress
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=natours_root_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=natours_root_password
      - ME_CONFIG_MONGODB_URL=mongodb://natours_root_user:natours_root_password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mongoexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mongoexpress
    links:
      - mongo
    restart: unless-stopped
